### ISSUE TITLE
SpUtil.putStringList(searchHistoryKey, searchHistoryList); 报错

### ISSUE THREAD

**Issue by HZRZCW** [Sky24n/sp_util#1]
报错内容是 Failed to download file from  with error.

**Comment by Sky24n** [comment]
请仔细确认错误信息。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by HZRZCW** [comment]
华为安卓手机荣耀30最新系统，报错内容只有CacheManager: Failed to download file from  with error

**Comment by HZRZCW** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (3 available)

• No issues found!

**Comment by Sky24n** [comment]
很明显你发的这个错是cached_network_image这个库报的


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
