### ISSUE TITLE
对象无法转换并存入

### ISSUE THREAD

**Issue by Shadow404** [Sky24n/sp_util#3]
Unhandled Exception: Converting object to an encodable object failed: Instance of 'FormSaveModel'
![image](https://user-images.githubusercontent.com/33001008/112708350-6ef66680-8eec-11eb-96c7-fb27197c2e85.png)

**Comment by Sky24n** [comment]
把toJson()加上

**Comment by Shadow404** [comment]
是加在我的那个实体类上吗，需要重新把实体类属性都写在tojson里？比如
![image](https://user-images.githubusercontent.com/33001008/112709081-3efd9200-8ef1-11eb-9cc3-5528334c90ea.png)
