### ISSUE TITLE
您好请问 我为什么取不到值,是我没存上吗 还是没取到

### ISSUE THREAD

**Issue by Caojunping** [Sky24n/sp_util#4]
class SplashPageState extends State<SplashPage> {
  //用户ID常量标识
  static const String SP_USER_ID = "sp_user_id";
  @override
  void initState() {
    super.initState();
    
    // App启动时读取Sp数据，需要异步等待Sp初始化完成。
    SpUtil.getInstance();

    // //存储数据USER_ID
    SpUtil.putString(SplashPageState.SP_USER_ID, 'CJP');

    // //获取数据USER_ID
    print('SpUtil === >${SpUtil.getString(SP_USER_ID, defValue: "")}');

**Comment by Caojunping** [comment]
这是打印结果:

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 935ms.
I/flutter (11877): SpUtil === >

**Comment by zhouying2019** [comment]
一样的问题，求解答

**Comment by Sky24n** [comment]
> 一样的问题，求解答

请认真看demo!
